import {
  siWordpress,
  siWoocommerce,
  siShopify,
  siWix,
  siSquarespace,
  siWebflow,
  siCraftcms,
  siYii,
  siTypo3,
  siUmbraco,
  siGhost,
  siContentful,
  siSanity,
  siStrapi,
  siPrestashop,
  siBigcommerce,
  siNextdotjs,
  siNuxt,
  siGatsby,
  siReact,
  siVuedotjs,
  siAngular,
  siSvelte,
  siAstro,
  siRemix,
  siEmberdotjs,
  siJquery,
  siBootstrap,
  siTailwindcss,
  siElementor,
  siDrupal,
  siJoomla,
  siLaravel,
  siSymfony,
  siDjango,
  siFlask,
  siRubyonrails,
  siExpress,
  siNodedotjs,
  siPython,
  siPhp,
  siDotnet,
  siPostgresql,
  siMysql,
  siMongodb,
  siRedis,
  siDocker,
  siGooglecloud,
  siDigitalocean,
  siFirebase,
  siSupabase,
  siRender,
  siCloudflare,
  siVercel,
  siNetlify,
  siNginx,
  siApache,
  siHubspot,
  siGoogletagmanager,
  siGoogleanalytics,
  siGooglefonts,
  siFontawesome,
  siStripe,
  siMailchimp,
  siHotjar,
  siSentry,
  siZapier,
  siTypeform,
  siCalendly,
  siIntercom,
  siZendesk,
  siMeta,
  siTiktok,
  siMatomo,
} from "simple-icons";

export interface TechIconData {
  title: string;
  path: string;
  hex: string;
}

// Covers both what the auto-detector (server/stackDetect.js) can find AND
// common technologies you might type in manually. Anything not in here
// (e.g. AWS, Magento, LinkedIn, Heroku, Azure — trademark-restricted, no
// icon exists in simple-icons) falls back to a plain text tag.
const ICONS: Record<string, TechIconData> = {
  // CMS / ecommerce
  WordPress: siWordpress,
  WooCommerce: siWoocommerce,
  Shopify: siShopify,
  Wix: siWix,
  Squarespace: siSquarespace,
  Webflow: siWebflow,
  "Craft CMS": siCraftcms,
  Yii: siYii,
  TYPO3: siTypo3,
  Umbraco: siUmbraco,
  Ghost: siGhost,
  Contentful: siContentful,
  Sanity: siSanity,
  Strapi: siStrapi,
  PrestaShop: siPrestashop,
  BigCommerce: siBigcommerce,

  // Frontend frameworks
  "Next.js": siNextdotjs,
  Nuxt: siNuxt,
  Gatsby: siGatsby,
  React: siReact,
  "Vue.js": siVuedotjs,
  Angular: siAngular,
  Svelte: siSvelte,
  Astro: siAstro,
  Remix: siRemix,
  "Ember.js": siEmberdotjs,
  jQuery: siJquery,
  Bootstrap: siBootstrap,
  "Tailwind CSS": siTailwindcss,
  Elementor: siElementor,
  Drupal: siDrupal,
  Joomla: siJoomla,

  // Backend frameworks / languages
  Laravel: siLaravel,
  Symfony: siSymfony,
  Django: siDjango,
  Flask: siFlask,
  "Ruby on Rails": siRubyonrails,
  Express: siExpress,
  "Node.js": siNodedotjs,
  Python: siPython,
  PHP: siPhp,
  "ASP.NET": siDotnet,

  // Databases / infra
  PostgreSQL: siPostgresql,
  MySQL: siMysql,
  MongoDB: siMongodb,
  Redis: siRedis,
  Docker: siDocker,
  "Google Cloud": siGooglecloud,
  DigitalOcean: siDigitalocean,
  Firebase: siFirebase,
  Supabase: siSupabase,
  Render: siRender,
  Cloudflare: siCloudflare,
  Vercel: siVercel,
  Netlify: siNetlify,
  Nginx: siNginx,
  Apache: siApache,

  // Marketing / analytics
  HubSpot: siHubspot,
  "Google Tag Manager": siGoogletagmanager,
  "Google Analytics": siGoogleanalytics,
  "Google Fonts": siGooglefonts,
  "Font Awesome": siFontawesome,
  Stripe: siStripe,
  Mailchimp: siMailchimp,
  Hotjar: siHotjar,
  Sentry: siSentry,
  Zapier: siZapier,
  Typeform: siTypeform,
  Calendly: siCalendly,
  Intercom: siIntercom,
  Zendesk: siZendesk,
  Meta: siMeta,
  TikTok: siTiktok,
  Matomo: siMatomo,
};

export function getTechIcon(name: string): TechIconData | null {
  return ICONS[name] ?? null;
}
